### PR TITLE
Offsets, nvpatch, minor UI changes etc

### PR DESCRIPTION
**Pull request by arx8x**
**Changes**

- adds nvpatch
- better offset loading(changes to C sysctl and ditches Objective C objects and their methods)
- exit out from remount call if offset isn't found
- log a test offset 
- change statusbar to light
- log version and buildid when view loads( I don't know why we're showing kern version)

**Notes**
- this combines offsets from previous PRs. So you can merge them
- All OFFSET_ROOT_MOUNT_V_NODE offsets `E T A S O N`

### CODE REVIEW

**Comment by frankthedead** [comment]
Do you have any issues with the bootstrap?

**Comment by Danoded** [comment]
^^ always rebooting on bootstrap.

**Comment by arx8x** [comment]
image

**Comment by frankthedead** [comment]
Fuck, there is something wrong with my build.

**Comment by frankthedead** [comment]
Tried to use you pull request, but:

captura de tela 2017-12-30 as 13 05 37

**Comment by arx8x** [comment]
That's weird. Did you clone my fork? If not, try that

**Comment by Dennisbonke** [comment]
commented out the nvpatch part, but xcode refuses to build it into an ipa for me to sideload, pastebin log: https://pastebin.com/LxafkuQR

**Comment by frankthedead** [comment]
@arx8x Yeah.

**Comment by arx8x** [comment]
Try now

**Comment by frankthedead** [comment]
It's compiled, let's see if bootstrap is gonna pass.

**Comment by frankthedead** [comment]
Failed to remount system partition.

**Comment by frankthedead** [comment]
Yeah, I fixed the offsets but still reboots on bootstrap.

**Comment by arx8x** [comment]
I'll have all the OFFSET_ROOT_MOUNT_V_NODE  soon

**Comment by frankthedead** [comment]
I think Sticktron is gonna fix the bootstrap soon.

**Comment by xNako** [comment]
Cydia crash

**Comment by xNako** [comment]
OFFSET_ROOT_MOUNT_V_NODE are the same of OFFSET_ROOTVNODE

**Comment by Danoded** [comment]
Offsets for 6s, 10.3.1 are wrong, unless they're for the TSMC chip (N71mAP). I have the ones for the Samsung chip (N71AP)

**Comment by Danoded** [comment]
Excuse me, they're legitimate.

**Comment by arx8x** [comment]
@Danoded 

They both have the same kernel. My code parses buildmanifest selects kernel for each boardconfig

capture2
capture

**Comment by Danoded** [comment]
Yeah that was an error on my part, apologies.

**Comment by xNako** [comment]
Also, don't call it here: uint64_t OFFSET_ROOTVNODE;

**Comment by arx8x** [comment]
Yeah, that along with other unused offsets will be removed. I gotta sleep now

**Comment by frankthedead** [comment]
Guys, I rebooted the phone into non-jailbreak mode, and when I tried to jailbreak again, I get the message jailbroke yo but it reboots after that, it's not supposed to just kill the springboard?

**Review by GithubPagesStuff — APPROVED** [review]
Approve Now. helps me alot so i dont have to read a giant diff

**Comment by arx8x** [comment]
@GithubPagesStuff I'll have to update my PR. I was gonna do that yesterday but then I decided I'll do it after @Sticktron sorts everything out. It's also an excuse since I had a terrible wrist plain :P

**Comment by swing7wing** [comment]
Why did you close this pull request?

**Comment by swing7wing** [comment]
Nvm you made a new one

**Pull request closed without merging**
